name: Tests

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  CLICOLOR_FORCE: 1
  RUSTDOCFLAGS: "-Dwarnings"

jobs:
  test-latest:
    name: Test on Latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: make test

  test-stable:
    name: Test on 1.64.0
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.64.0
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo run -p cargo-insta -- test
        
  test-current-cargo-insta:
    name: Run the in-tree version of cargo-insta on ourselves
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo run -p cargo-insta -- test

  build-old-stable:
    name: Check on MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-msrv
      - uses: Swatinem/rust-cache@v2
      - name: Verify minimum rust version
        run: make check-msrv

  test-latest-dependencies:
    name: Test latest deps
    # Note that we don't test MSRV after running `cargo update`, since that
    # would increase our maintenance burden â€” we'd need to be constantly pinning
    # sub-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo update
      - name: Test
        run: make test

  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: doc
        run: cargo doc --all-features
